### ISSUE TITLE
Get rid of the pesky warning from rat.dm

### ISSUE THREAD

**Issue by AnonymousHybi** [ARF-SS13/Project-Viper#2]
> code\modules\mob\living\simple_animal\vore\rat.dm:73:warning: : statement has no effect

`	if(food_dist > world.view) //Lose interest on this person.`
`		food = null`
`		Clamp(hunger+5, 0, 25)`

**Comment by AnonymousHybi** [comment]
I can't figure out what are the consequences for commenting this cancer out, I didn't even know we had math functions in unity that complicated.

would be useful for the inexperienced to know what clamp does. It caps the variable between a minimum value and a max value. Unity's definition:

> Clamps a value between a minimum float and maximum float value.

**Comment by AnonymousHybi** [comment]
Wait, we can just wait for god damn fix on virgo's end.

**Comment by TalkingCactus** [comment]
it's already there, yeah
